apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}
spec:
  description: Scoped project for PE workshop attendees
  destinations:
  {{- range .Values.destinations }}
    - namespace: {{ .namespace }}
      server: {{ .server }}
  {{- end }}
  sourceRepos:
  {{- range .Values.sourceRepos }}
    - {{ . }}
  {{- end }}
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
