projectName: pe-workshop
namespace: openshift-gitops

sourceRepos: []

destinations:
  - namespace: rhdh
    server: https://kubernetes.default.svc
  - namespace: prerequisite-samples
    server: https://kubernetes.default.svc
