projectName: pe-workshop
namespace: openshift-gitops

sourceRepos:
  - 'https://gitlab-gitlab.*.dyn.redhatworkshops.io/rhdh/*'
  - 'https://gitlab-gitlab.*.dyn.redhatworkshops.io/parasol/*'

destinations:
  - namespace: rhdh
    server: https://kubernetes.default.svc
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: prerequisite-samples
    server: https://kubernetes.default.svc
  - namespace: dev-team-alpha
    server: https://kubernetes.default.svc
